namespace MultiChannelAgent.Domain.Turns;

/// <summary>
/// Strongly typed identity generated by the application for each accepted <see cref="InboundTurn"/>.
/// Stable across retries so mutation and delivery work is never rerun once completed.
/// </summary>
public readonly record struct TurnId(Guid Value)
{
    public static TurnId NewId() => new(Guid.NewGuid());

    public override string ToString() => Value.ToString();
}
